name: Bug Report
title: "[ BUG ] "
description: Bug Report for conjure.wizardops.dev

labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: >-
        > [!IMPORTANT]

        > **This is not the place to report bugs for Conjure the CLI tool**. This form should be used to report a bug in [conjure.wizardops.dev](https://conjure.wizardops.dev).
  - type: dropdown
    id: dropdown-0
    attributes:
      label: Browser on which this bug occurs
      options:
        - Google Chrome
        - Microsoft Edge
        - Safari
        - Mozilla Firefox
        - Opera
        - Brave
        - Other (Specify Below)
      default: 0
  - type: textarea
    id: textarea-1
    attributes:
      value: Put the behavior you expected from the site here.
      label: Expected Behavior
  - type: textarea
    id: textarea-2
    attributes:
      value: Put the behavior you actually got from the site here.
      label: Actual Behavior
  - type: textarea
    id: textarea-3
    attributes:
      value: Put any extra information you can include here.
      label: Extra Details